create table items
(
    id          bigint generated by default as identity
        constraint items_pkey
            primary key,
    body        varchar(255),
    heading     varchar(255),
    time_create timestamp,
    time_update timestamp,
    user_id     bigint
);

alter table items
    owner to postgres