create table tags
(
   id bigint generated by default as identity
        constraint tags_pkey
            primary key,
    name varchar(255),
    time_create timestamp
);

alter table tags
    owner to postgres;

