create table users
(
    id bigint generated by default as identity
        constraint users_pkey
            primary key,
    login varchar(255),
    password varchar(255),
    nick_name varchar(255),
    time_reg timestamp
);

alter table users
    owner to postgres;